version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

python:
  install:
  - requirements: en/requirements.txt

sphinx:
  configuration: en/conf.py

  

# Build PDF & ePub
formats:
  - epub
  - pdf  
