version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"

submodules:
  include: all
  recursive: true

sphinx:
  configuration: content/cs/conf.py

python:
  install:
    - requirements: content/cs/requirements.txt

# Build PDF & ePub
formats:
  - epub
  - pdf  

environment:
  BRAND_VAR_PATH: ../brand_variables.py