# -*- coding: utf-8 -*-
#
# Whalebone documentation build configuration file, created by
# sphinx-quickstart on Wed Jan  4 17:02:40 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import os
import importlib.util
import shutil

# -- General configuration ------------------------------------------------

def get_product():
    product_var_path = os.environ.get("PRODUCT_VAR_PATH", "../../product_variables.py")
    spec = importlib.util.spec_from_file_location("product_variables", product_var_path)
    product_variables = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(product_variables)
    return product_variables.PRODUCT['product']

def create_index():
    index_rst = "index.rst"
    index_rst_lang = f"index_{get_product()}.rst".lower()
    try:
        os.remove(index_rst)
    except Exception:
        pass
    shutil.copyfile(index_rst_lang, index_rst)

def setup(app):
    app.tags.add(get_product())

rst_prolog = f""".. |product| replace:: {get_product()}"""

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = {'.rst': 'restructuredtext'}

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Whalebone'
copyright = '2026, Whalebone, s.r.o'
author = 'Whalebone'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '4.0'
# The full version, including alpha/beta/rc tags.
release = '4.0.0-1'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = [
    '_build', 'Thumbs.db', '.DS_Store', 'index_immunity.rst', 'index_peacemaker.rst',
    'index_aupdns.rst', 'index_aura.rst', 'index_dns4gov.rst']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

html_show_sourcelink = False

html_theme = 'sphinx_rtd_theme'
# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_sidebars = {
    "**": [
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/scroll-start.html",
        "sidebar/navigation.html",
        "sidebar/scroll-end.html",
        "sidebar/variant-selector.html",
    ]
}
html_title = "Whalebone Documentation"

html_theme_options = {
    'logo_only': True,
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': False,
    'titles_only': False,
    'version_selector': False,
    'language_selector': False
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'default.css',
]

html_logo = os.path.join('_static', 'whalebone_logo_white.png')

# Output file base name for HTML help builder.
htmlhelp_basename = 'Whalebonedoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'Whalebone.tex', 'Whalebone admin guide', '', 'manual')
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'whalebone', 'Whalebone admin guide', [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'Whalebone', 'Whalebone admin guide',
     author, 'Whalebone', 'Filter online threats off your network',
     'Miscellaneous'),
]


#remove blank pages from pdf
latex_elements = {
  'classoptions': ',openany,oneside',
  'babel': '\\usepackage[english]{babel}'
}
