name: Update Submodules in Brand Branches

on:
  push:
    branches:
      - master  # Trigger when the master branch is updated

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target_branch: [Immunity, Peacemaker, Aura, DNS4GOV]  # Add your branches here

    steps:
      - name: Checkout target branch ${{ matrix.target_branch }}
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.target_branch }}
          submodules: recursive
          token: ${{ secrets.UPDATE_DOC_CONTENT }}

      - name: Update submodule to latest commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Fetch the latest submodule commit
          #git submodule update --remote content
          cd content
          git pull origin master
          cd ..

          # Stage and commit if there are changes
          if ! git diff --quiet; then
            git add content
            git commit -m "Update submodule to the latest commit version"
            git push origin ${{ matrix.target_branch }}
          else
            echo "No changes to commit for ${{ matrix.target_branch }}"
          fi
